package com.liangxiaoqiao.leetcode.day.easy;


/*
 * English
 * id: 389
 * title: Find the Difference
 * href: https://leetcode.com/problems/find-the-difference
 * desc: Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 * <p>
 * 中文
 * 序号: 389
 * 标题： 找不同
 * 链接： https://leetcode-cn.com/problems/find-the-difference
 * 描述： 给定两个字符串 s 和 t，它们只包含小写字母。\n字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母。\n请找出在 t 中被添加的字母。\n  示例:\n输入：\ns = \"abcd\"\nt = \"abcde\"\n\n输出：\ne\n\n解释：\n\'e\' 是那个被添加的字母。
 * <p>
 * acceptance: 54.1%
 * difficulty: Easy
 * private: False
 */


//TODO init
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        return 0;
    }
}